version: 2
jobs:
  code_quality:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/aha
    steps:
      - checkout
      - run:
          command: yarn && yarn lint && yarn flow
workflows:
  version: 2
  build_test:
    jobs:
      - code_quality
