version: 2
jobs:
  frontend_lint:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/aha
    steps:
      - checkout
      - run:
          command: yarn && yarn lint
  frontend_flow:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/aha
    steps:
      - checkout
      - run:
          command: yarn && yarn flow
workflows:
  version: 2
  build_test:
    jobs:
      - frontend_lint
      - frontend_lint